#!/data/data/com.termux/files/usr/bin/bash

if ! command -v proot-distro
then
  printf "No 'proot-distro' command\n"
  exit 0
fi

proot_distro="/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs"

global_option=""

options=("Yes" "No")
distros="$(ls "$proot_distro")"
IFS=$'\n'
read -rd '' -a distros <<< "$distros"

yes_or_not=""
distro=""

IFS=

function pad() {
	local pos="$1"
	local string="$2"
	local pad_with="$3"
	local until=$4

	local pad_string=""
	for ((i = 0; i < until; i++)); do
		pad_string+="$pad_with"
	done

	local padded_string=""

	case "$pos" in
		'start')
			padded_string+="$pad_string$string"
			;;
		'end')
			padded_string+="$string$pad_string"
			;;
	esac

	printf "%s" "$padded_string"
}

function get_users_list() {
	local distro="$1"
	grep -oP "(?<=/home/).+(?=:)" "$proot_distro/$distro/etc/passwd"
}

function print_opts() {
	local all_opts=("$@")
	
	local valid_index="${all_opts[-1]}"
	unset 'all_opts[-1]'
	local label_size=$((${all_opts[-1]}))
	unset 'all_opts[-1]'
	
	local optprefix="\033[0m"
	local optsize="${#all_opts[@]}"
	local suffix

	local index=0
	for opt in "${all_opts[@]}"; do
		if ((index > 0)); then
			optprefix+="$(pad start '' ' ' $label_size)"
		fi

		if ((index == valid_index)); then
			optprefix+="\033[1m\033[38;5;51m"
			suffix=" <"
		else
			optprefix+="\033[22m\033[38;5;15m"
			suffix="\033[0K"
		fi

		if ((index > -1 && index < optsize - 1)); then
			suffix+="\n"
		else
			suffix+=""
		fi

		printf "$optprefix%s$suffix" "$opt"
		index=$((index + 1))
	done
}

function lines_to_up() {
	local lines="$1"
	if ((lines == 0)); then
		printf "\r"
	else
		printf "\033[%sA\r" "$lines"
	fi
}

function show_opts() {
	NOAN="\033[0m"
	local all_opts=("$@")

	local valid_index=0

	local label="${all_opts[-1]}"
	unset 'all_opts[-1]'
	local opts_size=${#all_opts[@]}
	local lines_up=$((${#all_opts[@]} - 1))
	local label_real
	label_real="$(echo -e "$label" | sed "s/$(echo -e "\033")[^m]*m//g")"
	local label_real_length=$((${#label_real}))
	
	local index
	local optprefix=""
	local esc_char
	esc_char=$(printf "\u1b")
	local selected
	printf "\033[0m%s" "$label"
	print_opts "${all_opts[@]}" $label_real_length $valid_index
	lines_to_up "$lines_up"
	while true; do
		read -rsn1 key
		if [[ $key == "$esc_char" ]]; then
			read -rsn2 key
		fi
		case $key in
			'[A')
				if ((valid_index < opts_size && valid_index > -1)); then
					valid_index=$((valid_index - 1))
				fi
				;;
			'[B')
				if ((valid_index > -1 && valid_index < opts_size)); then
					valid_index=$((valid_index + 1))
				fi
				;;
			"")
				break
				;;
		esac
		if ((valid_index < 0)); then
			valid_index=$((opts_size - 1))
		elif ((valid_index > opts_size - 1)); then
			valid_index=0
		fi
		printf "\r\033[0m%s" "$label"
		print_opts "${all_opts[@]}" $label_real_length $valid_index
		lines_to_up "$lines_up"
	done
	selected="${all_opts[$valid_index]}"
	global_option="$selected"
	printf "\033[30m\r%s\033[38;5;15m%s${NOAN}\033[0J\n" "$label" "$selected"
}

prompt=$' \033[32m>\033[1;37m '

show_opts "${options[@]}" "${prompt}Start on proot-distro?: "
yes_or_not="$global_option"
if [[ $yes_or_not == "No" ]]; then
	exit 0
fi

show_opts "${distros[@]}" "${prompt}Select a distro: "
distro="$global_option"

users_list=("$(get_users_list "$distro")")
users_list+=("root")

if [[ "${users_list[0]}" == "" ]]; then
	unset 'users_list[0]'
fi

show_opts "${users_list[@]}" "${prompt}Select a user: "
user="$global_option"

show_opts "${options[@]}" "${prompt}Exit instantly when log out?: "
exit_now="$global_option"

comm="proot-distro login "
comm+="$distro "
if [[ $user != "root" ]]; then
	comm+=" --user $user"
fi

eval "$comm"

if [[ "$exit_now" == "Yes" ]]; then
	exit 0
else
	return
fi
