#!/data/data/com.termux/files/usr/bin/bash

proot_distro="/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs"

global_option=""

options=("Yes" "No")
distros="$(ls "$proot_distro")"
IFS=$'\n'
read -rd '' -a distros <<< "$distros"

yes_or_not=""
distro=""

IFS=

function pad() {
	local pos="$1"
	local string="$2"
	local pad_with="$3"
	local until=$4

	local pad_string=""
	for ((i = 0; i < until; i++)); do
		pad_string+="$pad_with"
	done

	local padded_string=""

	case "$pos" in
		'start')
			padded_string+="$pad_string$string"
			;;
		'end')
			padded_string+="$string$pad_string"
	esac

	printf "$padded_string"
}

function get_users_list() {
	local distro="$1"
	grep -oP "(?<=/home/).+(?=:)" "$proot_distro/$distro/etc/passwd"
}

function print_opts() {
	local all_opts=("$@")
	
	local valid_index="${all_opts[-1]}"
	unset 'all_opts[-1]'
	local label_size="${all_opts[-1]}"
	unset 'all_opts[-1]'
	
	local optprefix
	local optsize="${#all_opts[@]}"
	local suffix=""

	local index=0
	for opt in "${all_opts[@]}"; do
		if ((index > 0)); then
			optprefix="$(pad start '' ' ' $label_size)"
		else
			optprefix=""
		fi

		if ((index == valid_index)); then
			optprefix+="\033[1;36m"
		else
			optprefix+="\033[0m"
		fi

		if ((index > -1 && index < optsize - 1)); then
			suffix="\n"
		else
			suffix=""
		fi

		printf "$optprefix%s$suffix" "$opt"
		index=$((index + 1))
	done
}

function lines_to_up() {
	local lines="$1"
	if ((lines == 0)); then
		printf "\r"
	else
		printf "\033[%sA\r" "$lines"
	fi
}

function show_opts() {
	NOAN="\033[0m"
	local all_opts=("$@")
	local valid_index=${all_opts[-1]}
	unset 'all_opts[-1]'
	local label="${all_opts[-1]}"
	unset 'all_opts[-1]'
	local opts_size=${#all_opts[@]}
	local lines_up=$((${#all_opts[@]} - 1))
	
	local index
	local optprefix=""
	local esc_char
	esc_char=$(printf "\u1b")
	local selected
	printf "\033[0m%s" "$label"
	print_opts "${all_opts[@]}" ${#label} $valid_index
	lines_to_up "$lines_up"
	while true; do
		read -rsn1 key
		if [[ $key == "$esc_char" ]]; then
			read -rsn2 key
		fi
		case $key in
			'[A')
				if ((valid_index < opts_size && valid_index > -1)); then
					valid_index=$((valid_index - 1))
				fi
				;;
			'[B')
				if ((valid_index > -1 && valid_index < opts_size)); then
					valid_index=$((valid_index + 1))
				fi
				;;
			"")
				break
				;;
		esac
		if ((valid_index < 0)); then
			valid_index=$((opts_size - 1))
		elif ((valid_index > opts_size - 1)); then
			valid_index=0
		fi
		printf "\r\033[0m%s" "$label"
		print_opts "${all_opts[@]}" ${#label} $valid_index
		lines_to_up "$lines_up"
	done
	selected="${all_opts[$valid_index]}"
	global_option="$selected"
	printf "${NOAN}\r%s\033[1;36m%s\033[0J\n" "$label" "$selected"
}

show_opts "${options[@]}" "Start on proot-distro?: " 0
yes_or_not="$global_option"
if [[ $yes_or_not == "No" ]]; then
	return
fi

show_opts "${distros[@]}" "Select a distro: " 0
distro="$global_option"

users_list=("$(get_users_list "$distro")")
users_list+=("root")

if [[ "${users_list[0]}" == "" ]]; then
	unset 'users_list[0]'
fi

show_opts "${users_list[@]}" "Select a user: " 0
user="$global_option"

show_opts "${options[@]}" "Exit instantly when log out?: " 0
exit_now="$global_option"

comm="proot-distro login "
comm+="$distro "
if [[ $user != "root" ]]; then
	comm+=" --user $user"
fi

eval "$comm"

if [[ "$exit_now" == "Yes" ]]; then
	exit 0
else
	return
fi
